baseURL: "https://chenyhd.github.io/blog"
languageCode: "en-us"
title: "Blog"
theme: "hugo-PaperMod"

params:
  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: 如果自由能像空气